language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t riccardo/udemy-docker-kubernetes -f Dockerfile.dev .

script:
  - docker run -e CI=true riccardo/udemy-docker-kubernetes npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "udemy-docker-kubernete-course-v2"
  env: "UdemyDockerKuberneteCourseV2-env"
  bucket_name: "elasticbeanstalk-eu-central-1-045015727085"
  bucket_path: "udemy-docker-kubernete-course-v2"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
