language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t riccardo/udemy-docker-kubernetes -f Dockerfile.dev .

script:
  - docker run -e CI=true riccardo/udemy-docker-kubernetes npm run test
