language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t riccardo/udemy-docker-kubernetes -f Docker.dev .

script:
  - docker run riccardo/udemy-docker-kubernetes npm run test -- --coverage
